#!/bin/bash

success(){

    GREEN="\e[0;32m"
    NC="\e[0m"

    echo -e "${GREEN}SUCCESS${NC}"

}

fail(){

    RED="\e[0;31m"
    NC="\e[0m"

    echo -e "${RED}FAILED${NC}"

}

help(){

    echo
    echo "installer for my scripts"
    echo
    echo "usage: bash installer <arg>"
    echo
    echo
    echo "arguments:"
    echo "      -i, --install           install scripts"
    echo "      -r, --remove            remove scripts"
    echo "      -u, --update            update repository"
    echo "      -h, --help              display help"
    echo
    echo "NOTE: don't run updater as root!"
    echo

}

install(){

    if [[ $EUID -ne 0 ]]
    then
        echo "RUN AS ROOT!"
        exit 1
    fi

    SCRIPTS=($(/usr/bin/ls b-*))

    for SCRIPT in "${SCRIPTS[@]}"
    do

        echo -n "installing '${SCRIPT}'... "

        /usr/bin/cp "$SCRIPT" "/usr/bin/"

        if [[ $? -eq 0 ]]
        then

            /usr/bin/chmod 555 "/usr/bin/${SCRIPT}"

            if [[ $? -eq 0 ]]
            then
                success
            else
                fail
                echo "ERROR: failed make '${SCRIPT}' executable"
            fi
        else
            fail
            echo "ERROR: failed to copy '${SCRIPT}' to '/usr/bin'"
        fi
    done
}

remove(){

    if [[ $EUID -ne 0 ]]
    then
        echo "RUN AS ROOT!"
        exit 1
    fi

    SCRIPTS=($(/usr/bin/ls b-*))

    for SCRIPT in "${SCRIPTS[@]}"
    do

        echo -n "removing '${SCRIPT}'... "

        /usr/bin/rm "/usr/bin/${SCRIPT}"

        if [[ $? -eq 0 ]]
        then
            success
        else
            fail
        fi
    done
}

update(){

    if [[ $EUID -eq 0 ]]
    then
        echo "DON'T RUN AS ROOT!"
        exit 1
    fi

    /usr/bin/git pull

}

case $1 in
    "-i" | "--install")
        install
        ;;
    "-r" | "--remove")
        remove
        ;;
    "-u" | "--update")
        update
        ;;
    "-h" | "--help")
        help
        ;;
    *)
        echo "ERROR: invalid argument: '$1'"
        echo "use '-h' or '--help' for help"
        exit 1
        ;;
esac
